# EUDR supplier geometry validator
### Demo: Product 1 of the EUDR portfolio

This notebook runs the validator against a supplier file that is **synthetic and deliberately dirty**
(set in real forestry areas of Corrientes and Misiones, Argentina, with fictitious names and
coordinates) to show the full flow: **ingestion → validation → conforming GeoJSON → quality report**.

See `README.md` for the regulatory detail of each check.

In [1]:
import sys, os
sys.path.insert(0, os.path.abspath(".."))

from main import run
import pandas as pd
pd.set_option("display.max_colwidth", 100)

## 1. Run the validator on the supplier Excel spreadsheet

"Long" format: one row per vertex. 15 parcels, some valid, others with deliberately
seeded errors (missing coordinates, inconsistent country, overlapping
parcels, etc.).

In [2]:
result = run("../data/synthetic_supplier_spreadsheet.xlsx", "../outputs/demo_excel")

print(f"Parcels in the output GeoJSON: {result['n_output_features']}")
print(f"Parcels excluded due to blocking error: {result['n_excluded_parcels']}")
print(f"Total findings: {len(result['findings'])}")

Parcels in the output GeoJSON: 7
Parcels excluded due to blocking error: 8
Total findings: 19

## 2. View the findings as a table

In [3]:
rows = [
    {"Severity": f.severity, "ParcelID": f.parcel_id, "Code": f.code,
     "Message": f.message, "Basis": f.reference}
    for f in sorted(result["findings"], key=lambda f: f.sort_key())
]
df_findings = pd.DataFrame(rows)
df_findings

,Severity,ParcelID,Code,Message,Basis
0,ERROR,MSNS-011-INVALIDISO,COUNTRY_INVALID_ISO,'ZZ' is not a valid ISO 3166-1 alpha-2 code.,EUDR GeoJSON File Description v1.5
1,ERROR,MSNS-006-LATLONSWAP,COUNTRY_MISMATCH,ProducerCountry='AR' does not match the actual location of the geometry (the parcel centroid fal...,EUDR GeoJSON File Description v1.5
2,ERROR,MSNS-014-SELFINTERSECT,GEOM_SELF_INTERSECTION,"The vertex sequence produces an invalid geometry (self-intersecting, figure-eight shape). Check ...",EUDR GeoJSON File Description v1.5
3,ERROR,MSNS-003-MISSINGLATLON,ING_MISSING_LATLON,Latitude or Longitude is missing.,Product 1: tabular input schema
4,ERROR,MSNS-004-TWOVERTICES,ING_TWO_VERTICES,The parcel has exactly 2 vertex rows: not enough for a polygon (minimum 3 distinct vertices) and...,Product 1: tabular input schema
5,ERROR,MSNS-010-OVERLAP-A / MSNS-010-OVERLAP-B,PARCELS_OVERLAP,Parcel 'MSNS-010-OVERLAP-A' overlaps with 'MSNS-010-OVERLAP-B' by 7.170 ha.,EUDR GeoJSON File Description v1.5
6,ERROR,MSNS-008-4HAVIOLATION,RULE_4HA_VIOLATION,Declared Area = 8.0 ha (> 4 ha) but the geometry is a Point. Parcels larger than 4 ha must be de...,"Regulation (EU) 2023/1115, Art. 9"
7,WARNING,MSNS-013-AREAMISMATCH,AREA_MISMATCH,The computed area of the geometry (14.94 ha) exceeds 4 ha but the declared Area (1.5 ha) does no...,EUDR GeoJSON File Description v1.5
8,WARNING,MSNS-007-PRECISION,COORD_PRECISION,The longitude has 14 decimal places (recommended maximum: 6). More than 6 decimals can produce d...,EUDR GeoJSON File Description v1.5
9,WARNING,MSNS-007-PRECISION,COORD_PRECISION,The latitude has 14 decimal places (recommended maximum: 6). More than 6 decimals can produce du...,EUDR GeoJSON File Description v1.5
10,WARNING,MSNS-005-INCONSISTENT,ING_METADATA_INCONSISTENT,"The property 'ProducerCountry' has different values across rows of the same parcel (['AR', 'BR']...",Product 1: metadata consistency per ParcelID
11,WARNING,MSNS-009-NOAREA,POINT_NO_AREA,"The parcel is a Point with no declared Area. The Information System will assume 4 ha by default,...",EUDR GeoJSON File Description v1.5
12,WARNING,MSNS-012-NOSPECIES,SPECIES_MISSING,"Missing: CommonName, ScientificName. For wood, the due diligence statement requires the common n...","Implementing Regulation (EU) 2024/3084, Art. 4"
13,INFO,MSNS-002,ING_AUTOCLOSE,The polygon was closed automatically by repeating the first vertex at the end (the source file d...,Product 1: tabular to GeoJSON conversion
14,INFO,MSNS-005-INCONSISTENT,ING_AUTOCLOSE,The polygon was closed automatically by repeating the first vertex at the end (the source file d...,Product 1: tabular to GeoJSON conversion
15,INFO,MSNS-010-OVERLAP-A,ING_AUTOCLOSE,The polygon was closed automatically by repeating the first vertex at the end (the source file d...,Product 1: tabular to GeoJSON conversion
16,INFO,MSNS-010-OVERLAP-B,ING_AUTOCLOSE,The polygon was closed automatically by repeating the first vertex at the end (the source file d...,Product 1: tabular to GeoJSON conversion
17,INFO,MSNS-013-AREAMISMATCH,ING_AUTOCLOSE,The polygon was closed automatically by repeating the first vertex at the end (the source file d...,Product 1: tabular to GeoJSON conversion
18,INFO,MSNS-014-SELFINTERSECT,ING_AUTOCLOSE,The polygon was closed automatically by repeating the first vertex at the end (the source file d...,Product 1: tabular to GeoJSON conversion

## 3. Filter only the blocking errors

These are the parcels that did **not** make it into `output.geojson`. They are documented here so
the supplier can correct them.

In [4]:
df_findings[df_findings["Severity"] == "ERROR"]

,Severity,ParcelID,Code,Message,Basis
0,ERROR,MSNS-011-INVALIDISO,COUNTRY_INVALID_ISO,'ZZ' is not a valid ISO 3166-1 alpha-2 code.,EUDR GeoJSON File Description v1.5
1,ERROR,MSNS-006-LATLONSWAP,COUNTRY_MISMATCH,ProducerCountry='AR' does not match the actual location of the geometry (the parcel centroid fal...,EUDR GeoJSON File Description v1.5
2,ERROR,MSNS-014-SELFINTERSECT,GEOM_SELF_INTERSECTION,"The vertex sequence produces an invalid geometry (self-intersecting, figure-eight shape). Check ...",EUDR GeoJSON File Description v1.5
3,ERROR,MSNS-003-MISSINGLATLON,ING_MISSING_LATLON,Latitude or Longitude is missing.,Product 1: tabular input schema
4,ERROR,MSNS-004-TWOVERTICES,ING_TWO_VERTICES,The parcel has exactly 2 vertex rows: not enough for a polygon (minimum 3 distinct vertices) and...,Product 1: tabular input schema
5,ERROR,MSNS-010-OVERLAP-A / MSNS-010-OVERLAP-B,PARCELS_OVERLAP,Parcel 'MSNS-010-OVERLAP-A' overlaps with 'MSNS-010-OVERLAP-B' by 7.170 ha.,EUDR GeoJSON File Description v1.5
6,ERROR,MSNS-008-4HAVIOLATION,RULE_4HA_VIOLATION,Declared Area = 8.0 ha (> 4 ha) but the geometry is a Point. Parcels larger than 4 ha must be de...,"Regulation (EU) 2023/1115, Art. 9"

## 4. Inspect the output GeoJSON (conforming to v1.5)

In [5]:
import json

with open("../outputs/demo_excel/output.geojson", encoding="utf-8") as f:
    out = json.load(f)

print(f"type: {out['type']}")
print(f"features: {len(out['features'])}")
print()
print(json.dumps(out["features"][0], indent=2, ensure_ascii=False))

type: FeatureCollection
features: 7

{
  "type": "Feature",
  "properties": {
    "ProducerName": "Yerbatera San Ignacio",
    "ProducerCountry": "AR",
    "ProductionPlace": "Chacra 3",
    "Area": 1.8,
    "CommonName": "Pino",
    "ScientificName": "Pinus taeda"
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      -54.59,
      -26.4
    ]
  }
}

## 5. View the quality report (Markdown version)

The same content is available as `quality_report.pdf` and `quality_report.xlsx` in the
output folder, designed for a compliance team working in Excel/SAP, not in notebooks.

In [6]:
from IPython.display import Markdown, display

with open("../outputs/demo_excel/quality_report.md", encoding="utf-8") as f:
    display(Markdown(f.read()))

# Quality report: EUDR supplier geometry validator

**Input file:** `synthetic_supplier_spreadsheet.xlsx`
**Generated:** 2026-10-22 11:14
**Commodity:** Wood (Southern Cone)
**Reference format:** EUDR GeoJSON File Description v1.5 (Implementing Regulation (EU) 2024/3084)

## Executive summary

| Metric | Value |
|---|---|
| Parcels evaluated | 15 |
| Parcels ready to submit as-is | 7 |
| Parcels with blocking error | 8 |
| Blocking errors (total) | 7 |
| Warnings (non-blocking) | 6 |
| Conversion notes | 6 |

**What "ready" means:** the parcel has no finding of severity *Blocking error*. The output GeoJSON (`output.geojson`) contains only ready parcels. Parcels with a blocking error are left out of the output file and must be corrected at the source before attempting submission again.

## 🔴 Blocking errors (7)

- **[COUNTRY_INVALID_ISO]** Parcel `MSNS-011-INVALIDISO`: 'ZZ' is not a valid ISO 3166-1 alpha-2 code.
  *Basis: EUDR GeoJSON File Description v1.5*
- **[COUNTRY_MISMATCH]** Parcel `MSNS-006-LATLONSWAP`: ProducerCountry='AR' does not match the actual location of the geometry (the parcel centroid falls outside the declared country, even with a tolerance margin).
  *Basis: EUDR GeoJSON File Description v1.5*
- **[GEOM_SELF_INTERSECTION]** Parcel `MSNS-014-SELFINTERSECT`: The vertex sequence produces an invalid geometry (self-intersecting, figure-eight shape). Check the vertex order.
  *Basis: EUDR GeoJSON File Description v1.5*
- **[ING_MISSING_LATLON]** Parcel `MSNS-003-MISSINGLATLON`: Latitude or Longitude is missing.
  *Basis: Product 1: tabular input schema*
- **[ING_TWO_VERTICES]** Parcel `MSNS-004-TWOVERTICES`: The parcel has exactly 2 vertex rows: not enough for a polygon (minimum 3 distinct vertices) and not a single point. Check whether a vertex is missing or one was declared too many.
  *Basis: Product 1: tabular input schema*
- **[PARCELS_OVERLAP]** Parcel `MSNS-010-OVERLAP-A / MSNS-010-OVERLAP-B`: Parcel 'MSNS-010-OVERLAP-A' overlaps with 'MSNS-010-OVERLAP-B' by 7.170 ha.
  *Basis: EUDR GeoJSON File Description v1.5*
- **[RULE_4HA_VIOLATION]** Parcel `MSNS-008-4HAVIOLATION`: Declared Area = 8.0 ha (> 4 ha) but the geometry is a Point. Parcels larger than 4 ha must be declared as a polygon, with enough vertices to describe the perimeter.
  *Basis: Regulation (EU) 2023/1115, Art. 9*

## 🟡 Warnings (6)

- **[AREA_MISMATCH]** Parcel `MSNS-013-AREAMISMATCH`: The computed area of the geometry (14.94 ha) exceeds 4 ha but the declared Area (1.5 ha) does not. Check which of the two values is correct.
  *Basis: EUDR GeoJSON File Description v1.5*
- **[COORD_PRECISION]** Parcel `MSNS-007-PRECISION`: The longitude has 14 decimal places (recommended maximum: 6). More than 6 decimals can produce duplicate coordinates through rounding when processed by the system.
  *Basis: EUDR GeoJSON File Description v1.5*
- **[COORD_PRECISION]** Parcel `MSNS-007-PRECISION`: The latitude has 14 decimal places (recommended maximum: 6). More than 6 decimals can produce duplicate coordinates through rounding when processed by the system.
  *Basis: EUDR GeoJSON File Description v1.5*
- **[ING_METADATA_INCONSISTENT]** Parcel `MSNS-005-INCONSISTENT`: The property 'ProducerCountry' has different values across rows of the same parcel (['AR', 'BR']); the first one was used.
  *Basis: Product 1: metadata consistency per ParcelID*
- **[POINT_NO_AREA]** Parcel `MSNS-009-NOAREA`: The parcel is a Point with no declared Area. The Information System will assume 4 ha by default, a silent risk if the real parcel is larger or smaller.
  *Basis: EUDR GeoJSON File Description v1.5*
- **[SPECIES_MISSING]** Parcel `MSNS-012-NOSPECIES`: Missing: CommonName, ScientificName. For wood, the due diligence statement requires the common name and full scientific name of the species.
  *Basis: Implementing Regulation (EU) 2024/3084, Art. 4*

## ℹ️ Conversion notes (6)

- **[ING_AUTOCLOSE]** Parcel `MSNS-002`: The polygon was closed automatically by repeating the first vertex at the end (the source file did not repeat it, which is common practice in spreadsheets).
  *Basis: Product 1: tabular to GeoJSON conversion*
- **[ING_AUTOCLOSE]** Parcel `MSNS-005-INCONSISTENT`: The polygon was closed automatically by repeating the first vertex at the end (the source file did not repeat it, which is common practice in spreadsheets).
  *Basis: Product 1: tabular to GeoJSON conversion*
- **[ING_AUTOCLOSE]** Parcel `MSNS-010-OVERLAP-A`: The polygon was closed automatically by repeating the first vertex at the end (the source file did not repeat it, which is common practice in spreadsheets).
  *Basis: Product 1: tabular to GeoJSON conversion*
- **[ING_AUTOCLOSE]** Parcel `MSNS-010-OVERLAP-B`: The polygon was closed automatically by repeating the first vertex at the end (the source file did not repeat it, which is common practice in spreadsheets).
  *Basis: Product 1: tabular to GeoJSON conversion*
- **[ING_AUTOCLOSE]** Parcel `MSNS-013-AREAMISMATCH`: The polygon was closed automatically by repeating the first vertex at the end (the source file did not repeat it, which is common practice in spreadsheets).
  *Basis: Product 1: tabular to GeoJSON conversion*
- **[ING_AUTOCLOSE]** Parcel `MSNS-014-SELFINTERSECT`: The polygon was closed automatically by repeating the first vertex at the end (the source file did not repeat it, which is common practice in spreadsheets).
  *Basis: Product 1: tabular to GeoJSON conversion*

## 6. Repeat with the raw GeoJSON file

Exercises the other ingestion path: a supplier that already sends GeoJSON, but with structural
errors (unclosed polygons, prohibited geometry types, incorrect property
capitalization, etc.).

In [7]:
result_geojson = run("../data/synthetic_geojson_input.geojson", "../outputs/demo_geojson")

print(f"Parcels in the output GeoJSON: {result_geojson['n_output_features']}")
print(f"Parcels excluded due to blocking error: {result_geojson['n_excluded_parcels']}")
print(f"Total findings: {len(result_geojson['findings'])}")

Parcels in the output GeoJSON: 7
Parcels excluded due to blocking error: 15
Total findings: 49

## 7. Test set: automatic verification

`tests/run_validation_test.py` runs this same flow against the 37 deliberately seeded errors and
verifies, code by code, that the validator detects all of them. It can be run from here:

In [8]:
!cd .. && python3 tests/run_validation_test.py

======================================================================
TEST 1: raw GeoJSON (synthetic_geojson_input.geojson)
======================================================================

  ✅ CTES-001: no findings (valid control)
  ✅ CTES-002: no findings (valid control)
  ✅ CTES-003-LINESTRING: OK ['GEOM_TYPE_PROHIBITED']
  ✅ CTES-004-GEOMCOLLECTION: OK ['GEOM_TYPE_PROHIBITED']
  ✅ CTES-005-HOLE: OK ['POLY_HAS_HOLES']  [+ extra, not evaluated: ['SPECIES_MISSING']]
  ✅ CTES-006-UNCLOSED: OK ['POLY_NOT_CLOSED']  [+ extra, not evaluated: ['SPECIES_MISSING']]
  ✅ CTES-007-SELFINTERSECT: OK ['GEOM_SELF_INTERSECTION']  [+ extra, not evaluated: ['COORD_PRECISION', 'SPECIES_MISSING']]
  ✅ CTES-008-PROPCASE: OK ['PROPERTY_CASE']  [+ extra, not evaluated: ['SPECIES_MISSING']]
  ✅ CTES-009-PRECISION: OK ['COORD_PRECISION']  [+ extra, not evaluated: ['SPECIES_MISSING']]
  ✅ CTES-010-COUNTRYMISMATCH: OK ['COUNTRY_MISMATCH']  [+ extra, not evaluated: ['SPECIES_MISSING']]
  ✅ CTES-011-INVALIDISO: OK ['COUNTRY_INVALID_ISO']  [+ extra, not evaluated: ['SPECIES_MISSING']]
  ✅ CTES-012-COUNTRYMISSING: OK ['COUNTRY_MISSING']  [+ extra, not evaluated: ['SPECIES_MISSING']]
  ✅ CTES-013-AREASTRING: OK ['AREA_NOT_NUMERIC']  [+ extra, not evaluated: ['SPECIES_MISSING']]
  ✅ CTES-014-POINT-NOAREA: OK ['POINT_NO_AREA']  [+ extra, not evaluated: ['SPECIES_MISSING']]
  ✅ CTES-015-4HAVIOLATION: OK ['RULE_4HA_VIOLATION']  [+ extra, not evaluated: ['SPECIES_MISSING']]
  ✅ CTES-016-TOOFEWVERTICES: OK ['POLY_TOO_FEW_VERTICES']  [+ extra, not evaluated: ['GEOM_SELF_INTERSECTION', 'SPECIES_MISSING']]
  ✅ CTES-017-OVERLAP-A: OK ['PARCELS_OVERLAP']  [+ extra, not evaluated: ['SPECIES_MISSING']]
  ✅ CTES-017-OVERLAP-B: OK ['PARCELS_OVERLAP']  [+ extra, not evaluated: ['SPECIES_MISSING']]
  ✅ CTES-018-NOSPECIES: OK ['SPECIES_MISSING']
  ✅ CTES-019-OUTOFRANGE: OK ['COORD_OUT_OF_RANGE']  [+ extra, not evaluated: ['COUNTRY_MISMATCH', 'SPECIES_MISSING']]
  ✅ CTES-020-DUP: OK ['DUPLICATE_PARCEL_ID']
  ✅ CTES-021-AREAMISMATCH: OK ['AREA_MISMATCH']

  Total findings: 49
  Parcels in output GeoJSON: 7
  Parcels excluded due to blocking error: 15

======================================================================
TEST 2: Excel spreadsheet (synthetic_supplier_spreadsheet.xlsx)
======================================================================

  ✅ MSNS-001: no findings (valid control)
  ✅ MSNS-002: OK ['ING_AUTOCLOSE']
  ✅ MSNS-003-MISSINGLATLON: OK ['ING_MISSING_LATLON']
  ✅ MSNS-004-TWOVERTICES: OK ['ING_TWO_VERTICES']
  ✅ MSNS-005-INCONSISTENT: OK ['ING_METADATA_INCONSISTENT']  [+ extra, not evaluated: ['ING_AUTOCLOSE']]
  ✅ MSNS-006-LATLONSWAP: OK ['COUNTRY_MISMATCH']
  ✅ MSNS-007-PRECISION: OK ['COORD_PRECISION']
  ✅ MSNS-008-4HAVIOLATION: OK ['RULE_4HA_VIOLATION']
  ✅ MSNS-009-NOAREA: OK ['POINT_NO_AREA']
  ✅ MSNS-010-OVERLAP-A: OK ['PARCELS_OVERLAP']  [+ extra, not evaluated: ['ING_AUTOCLOSE']]
  ✅ MSNS-010-OVERLAP-B: OK ['PARCELS_OVERLAP']  [+ extra, not evaluated: ['ING_AUTOCLOSE']]
  ✅ MSNS-011-INVALIDISO: OK ['COUNTRY_INVALID_ISO']
  ✅ MSNS-012-NOSPECIES: OK ['SPECIES_MISSING']
  ✅ MSNS-013-AREAMISMATCH: OK ['AREA_MISMATCH']  [+ extra, not evaluated: ['ING_AUTOCLOSE']]
  ✅ MSNS-014-SELFINTERSECT: OK ['GEOM_SELF_INTERSECTION']  [+ extra, not evaluated: ['ING_AUTOCLOSE']]

  Total findings: 19
  Parcels in output GeoJSON: 7
  Parcels excluded due to blocking error: 8

======================================================================
FINAL RESULT: ✅ the validator detected ALL seeded errors.